### ISSUE TITLE
Wrong prediction

### ISSUE THREAD

**Issue by diyaeapen** [suvrat06/Bhaav.ai#1]

**Comment by diyaeapen** [comment]
<img width="664" alt="Capture" src="https://user-images.githubusercontent.com/67554287/179364590-51a7e1fa-cbeb-4725-bce7-5346025f1197.PNG">
 I guess it is a wrong prediction. Can you help me out.

**Comment by suvrat06** [comment]
Hi! I guess you'd have swapped the variables that store the positive and negative scores. Please do check it once.
